version: '3.4'

services:
  lisbank.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5000:80"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  database:
    environment:
      - SA_PASSWORD=Password_0
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    ports:
      - "1443:1443"
